[workspace]
members = [
    "examples", # Examples
    "moqp", # Publish
    "moqr", # Relay
    "moqs", # Subscribe
    "moqt", # Transport
    "reserved/moqa", # Agent
    "reserved/moqb", # Broker
    "reserved/moqc", # Client
    "reserved/moqd", # Delegator
    "reserved/moqe", # Extension
    "reserved/moqf", # Format
    "reserved/moqg", # Geocode
    "reserved/moql", # Lite/LOC
    "reserved/moqm", # Media
    "reserved/moqn", # Network
    "reserved/moqw", # WebAssembly
]
resolver = "2"

[profile.dev]
opt-level = 0

[workspace.package]
version = "0.0.1"
authors = ["Rain Liu <y@liu.mx>"]
edition = "2024"
license = "MIT/Apache-2.0"
homepage = "https://moq.rs"
repository = "https://github.com/moq-rs/moq"
keywords = ["sansio", "networking", "protocols"]
categories = ["network-programming"]

[workspace.dependencies]
moqp = { version = "0.0.1", path = "moqp" }
moqr = { version = "0.0.1", path = "moqr" }
moqs = { version = "0.0.1", path = "moqs" }
moqt = { version = "0.0.1", path = "moqt" }

# common dependencies
sansio = "1.0.1"
bytes = "1.12.0"
byteorder = "1.5.0"
thiserror = "2.0.18"
log = "0.4.33"
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }

# dev dependencies
env_logger = "0.11.8"
chrono = "0.4.43"
clap = { version = "4.5.54", features = ["derive"] }
ctrlc = "3.5.1"
criterion = "0.8.1"
rstest = "0.26.1"
tokio = { version = "1.49.0", features = ["full"] }
