[workspace]
members = [
    "moqp", # Publish
    "moqr", # Relay
    "moqs", # Subscribe
    "moqt", # Transport
    "reserved/moqa", # Agent
    "reserved/moqb", # Broker
    "reserved/moqc", # Client
    "reserved/moqd", # Delegator
    "reserved/moqe", # Extension
    "reserved/moqf", # Format
    "reserved/moqg", # Geocode
    "reserved/moql", # Lite/LOC
    "reserved/moqm", # Media
    "reserved/moqn", # Network
    "reserved/moqw", # WebAssembly
]
resolver = "2"

[profile.dev]
opt-level = 0
