[package]
name = "moqt"
description = "Media over QUIC - Transport"
documentation = "https://docs.rs/moqt"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
sansio.workspace = true
bytes.workspace = true
thiserror.workspace = true
log.workspace = true

[dev-dependencies]
rstest.workspace = true
