[package]
name = "moqs"
version = "0.0.0"
authors = ["yngrtc <y@ngr.tc>"]
edition = "2021"
description = "Media over QUIC - Subscribe"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/moqs"
homepage = "https://moq.rs"
repository = "https://github.com/moq-rs/moq"

[dependencies]
